### ISSUE TITLE
ЕРП механ

### ISSUE THREAD

**Issue by LeShprotina** [Lambda-13/Civ13#5]
**Что добавить**
ЕРП механ

**Спрайты/скриншоты**
Спизди механ с Citadel Station

**Зачем**
Можно будет ебать Августа

**Дополнительно**
Я сладко дунул перед этим решением
![Торч](https://user-images.githubusercontent.com/87897445/141083720-1ba6ada0-743a-4c4e-b9e6-129f1972d57b.png)

**Comment by LeShprotina** [comment]
Ну вообще можно просто спиздить кусок с фолыча и работать тоже будет без лишней ебли.

**Comment by SanecMan** [comment]
В очереди, будет через неделю.
![image](https://user-images.githubusercontent.com/36476150/142412703-fdf0c9f3-b929-4182-9cc7-a93d554b7582.png)

**Comment by SanecMan** [comment]
Слишком занят, придётся повременить с ерп системой до следующего года.
