### ISSUE TITLE
Нельзя скрафтить патроны

### ISSUE THREAD

**Issue by VanoTyanochka** [Lambda-13/Civ13#8]
Люди единственные кто могут крафтить пушки но не могут крафтить патроны для пушек, а точнее кремниевые и мушкетные, ибо кодер хуесос

**Comment by SanecMan** [comment]
не могут и не надо

**Comment by VityaSchel** [comment]
ну кодер рили хуесос кста

**Comment by SanecMan** [comment]
сам такой
